/*
-- Query: SELECT postcode, post FROM sql7112186.posts
LIMIT 0, 1000

-- Date: 2016-04-05 09:48
*/
INSERT INTO posts (postcode,post) VALUES (1000,'Ljubljana ');
INSERT INTO posts (postcode,post) VALUES (1001,'Ljubljana - poštni predali');
INSERT INTO posts (postcode,post) VALUES (1002,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1101,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1108,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1110,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1111,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1113,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1117,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1119,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1120,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1126,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1129,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1131,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1133,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1210,'Ljubljana - Šentvid');
INSERT INTO posts (postcode,post) VALUES (1211,'Ljubljana - Šmartno');
INSERT INTO posts (postcode,post) VALUES (1215,'Medvode');
INSERT INTO posts (postcode,post) VALUES (1216,'Smlednik');
INSERT INTO posts (postcode,post) VALUES (1217,'Vodice');
INSERT INTO posts (postcode,post) VALUES (1218,'Komenda');
INSERT INTO posts (postcode,post) VALUES (1219,'Laze v Tuhinju');
INSERT INTO posts (postcode,post) VALUES (1221,'Motnik');
INSERT INTO posts (postcode,post) VALUES (1222,'Trojane');
INSERT INTO posts (postcode,post) VALUES (1223,'Blagovica');
INSERT INTO posts (postcode,post) VALUES (1225,'Lukovica');
INSERT INTO posts (postcode,post) VALUES (1230,'Domžale');
INSERT INTO posts (postcode,post) VALUES (1231,'Ljubljana - Crnuce');
INSERT INTO posts (postcode,post) VALUES (1233,'Dob');
INSERT INTO posts (postcode,post) VALUES (1234,'Mengeš');
INSERT INTO posts (postcode,post) VALUES (1235,'Radomlje');
INSERT INTO posts (postcode,post) VALUES (1236,'Trzin');
INSERT INTO posts (postcode,post) VALUES (1240,'Kamnik');
INSERT INTO posts (postcode,post) VALUES (1241,'Kamnik');
INSERT INTO posts (postcode,post) VALUES (1242,'Stahovica');
INSERT INTO posts (postcode,post) VALUES (1251,'Moravce');
INSERT INTO posts (postcode,post) VALUES (1252,'Vace');
INSERT INTO posts (postcode,post) VALUES (1260,'Ljubljana - Polje');
INSERT INTO posts (postcode,post) VALUES (1261,'Ljubljana - Dobrunje');
INSERT INTO posts (postcode,post) VALUES (1262,'Dol pri Ljubljani');
INSERT INTO posts (postcode,post) VALUES (1270,'Litija');
INSERT INTO posts (postcode,post) VALUES (1272,'Polšnik');
INSERT INTO posts (postcode,post) VALUES (1273,'Dole pri Litiji');
INSERT INTO posts (postcode,post) VALUES (1274,'Gabrovka');
INSERT INTO posts (postcode,post) VALUES (1275,'Šmartno pri Litiji');
INSERT INTO posts (postcode,post) VALUES (1276,'Primskovo ');
INSERT INTO posts (postcode,post) VALUES (1281,'Kresnice');
INSERT INTO posts (postcode,post) VALUES (1282,'Sava');
INSERT INTO posts (postcode,post) VALUES (1290,'Grosuplje');
INSERT INTO posts (postcode,post) VALUES (1291,'Škofljica');
INSERT INTO posts (postcode,post) VALUES (1292,'Ig');
INSERT INTO posts (postcode,post) VALUES (1293,'Šmarje - Sap');
INSERT INTO posts (postcode,post) VALUES (1294,'Višnja Gora');
INSERT INTO posts (postcode,post) VALUES (1295,'Ivancna Gorica');
INSERT INTO posts (postcode,post) VALUES (1296,'Šentvid pri Sticni');
INSERT INTO posts (postcode,post) VALUES (1301,'Krka');
INSERT INTO posts (postcode,post) VALUES (1303,'Zagradec');
INSERT INTO posts (postcode,post) VALUES (1310,'Ribnica');
INSERT INTO posts (postcode,post) VALUES (1311,'Turjak');
INSERT INTO posts (postcode,post) VALUES (1312,'Videm - Dobrepolje');
INSERT INTO posts (postcode,post) VALUES (1313,'Struge');
INSERT INTO posts (postcode,post) VALUES (1314,'Rob');
INSERT INTO posts (postcode,post) VALUES (1315,'Velike Lašce');
INSERT INTO posts (postcode,post) VALUES (1316,'Ortnek');
INSERT INTO posts (postcode,post) VALUES (1317,'Sodražica');
INSERT INTO posts (postcode,post) VALUES (1318,'Loški Potok');
INSERT INTO posts (postcode,post) VALUES (1319,'Draga');
INSERT INTO posts (postcode,post) VALUES (1330,'Kocevje');
INSERT INTO posts (postcode,post) VALUES (1331,'Dolenja vas');
INSERT INTO posts (postcode,post) VALUES (1332,'Stara Cerkev');
INSERT INTO posts (postcode,post) VALUES (1336,'Kostel');
INSERT INTO posts (postcode,post) VALUES (1337,'Osilnica');
INSERT INTO posts (postcode,post) VALUES (1338,'Kocevska Reka');
INSERT INTO posts (postcode,post) VALUES (1351,'Brezovica pri Ljubljani');
INSERT INTO posts (postcode,post) VALUES (1352,'Preserje');
INSERT INTO posts (postcode,post) VALUES (1353,'Borovnica');
INSERT INTO posts (postcode,post) VALUES (1354,'Horjul');
INSERT INTO posts (postcode,post) VALUES (1355,'Polhov Gradec');
INSERT INTO posts (postcode,post) VALUES (1356,'Dobrova');
INSERT INTO posts (postcode,post) VALUES (1357,'Notranje Gorice');
INSERT INTO posts (postcode,post) VALUES (1358,'Log pri Brezovici');
INSERT INTO posts (postcode,post) VALUES (1360,'Vrhnika');
INSERT INTO posts (postcode,post) VALUES (1370,'Logatec');
INSERT INTO posts (postcode,post) VALUES (1371,'Logatec');
INSERT INTO posts (postcode,post) VALUES (1372,'Hotedršica');
INSERT INTO posts (postcode,post) VALUES (1373,'Rovte');
INSERT INTO posts (postcode,post) VALUES (1380,'Cerknica');
INSERT INTO posts (postcode,post) VALUES (1381,'Rakek');
INSERT INTO posts (postcode,post) VALUES (1382,'Begunje pri Cerknici');
INSERT INTO posts (postcode,post) VALUES (1384,'Grahovo');
INSERT INTO posts (postcode,post) VALUES (1385,'Nova vas');
INSERT INTO posts (postcode,post) VALUES (1386,'Stari trg pri Ložu');
INSERT INTO posts (postcode,post) VALUES (1410,'Zagorje ob Savi');
INSERT INTO posts (postcode,post) VALUES (1411,'Izlake');
INSERT INTO posts (postcode,post) VALUES (1412,'Kisovec');
INSERT INTO posts (postcode,post) VALUES (1413,'Cemšenik');
INSERT INTO posts (postcode,post) VALUES (1414,'Podkum');
INSERT INTO posts (postcode,post) VALUES (1420,'Trbovlje');
INSERT INTO posts (postcode,post) VALUES (1423,'Dobovec');
INSERT INTO posts (postcode,post) VALUES (1430,'Hrastnik');
INSERT INTO posts (postcode,post) VALUES (1431,'Dol pri Hrastniku');
INSERT INTO posts (postcode,post) VALUES (1432,'Zidani Most');
INSERT INTO posts (postcode,post) VALUES (1433,'Radece');
INSERT INTO posts (postcode,post) VALUES (1434,'Loka pri Zidanem Mostu');
INSERT INTO posts (postcode,post) VALUES (1501,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1502,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1503,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1504,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1505,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1506,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1507,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1509,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1510,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1511,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1512,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1513,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1514,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1516,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1517,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1518,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1519,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1520,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1521,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1522,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1523,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1524,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1525,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1526,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1527,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1528,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1529,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1532,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1533,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1534,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1535,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1536,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1537,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1538,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1540,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1542,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1543,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1544,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1545,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1546,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1547,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1550,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (1600,'Ljubljana');
INSERT INTO posts (postcode,post) VALUES (2000,'Maribor ');
INSERT INTO posts (postcode,post) VALUES (2001,'Maribor - poštni predali');
INSERT INTO posts (postcode,post) VALUES (2002,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2103,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2201,'Zgornja Kungota');
INSERT INTO posts (postcode,post) VALUES (2204,'Miklavž na Dravskem polju');
INSERT INTO posts (postcode,post) VALUES (2205,'Starše');
INSERT INTO posts (postcode,post) VALUES (2206,'Marjeta na Dravskem polju');
INSERT INTO posts (postcode,post) VALUES (2208,'Pohorje');
INSERT INTO posts (postcode,post) VALUES (2211,'Pesnica pri Mariboru');
INSERT INTO posts (postcode,post) VALUES (2212,'Šentilj v Slovenskih goricah');
INSERT INTO posts (postcode,post) VALUES (2213,'Zgornja Velka');
INSERT INTO posts (postcode,post) VALUES (2214,'Sladki Vrh');
INSERT INTO posts (postcode,post) VALUES (2215,'Ceršak');
INSERT INTO posts (postcode,post) VALUES (2221,'Jarenina');
INSERT INTO posts (postcode,post) VALUES (2222,'Jakobski Dol');
INSERT INTO posts (postcode,post) VALUES (2223,'Jurovski Dol');
INSERT INTO posts (postcode,post) VALUES (2229,'Malecnik');
INSERT INTO posts (postcode,post) VALUES (2230,'Lenart v Slovenskih goricah');
INSERT INTO posts (postcode,post) VALUES (2231,'Pernica');
INSERT INTO posts (postcode,post) VALUES (2232,'Volicina');
INSERT INTO posts (postcode,post) VALUES (2233,'Sv. Ana v Slovenskih goricah');
INSERT INTO posts (postcode,post) VALUES (2234,'Benedikt');
INSERT INTO posts (postcode,post) VALUES (2235,'Sv. Trojica v Slovenskih goricah');
INSERT INTO posts (postcode,post) VALUES (2236,'Cerkvenjak');
INSERT INTO posts (postcode,post) VALUES (2241,'Spodnji Duplek');
INSERT INTO posts (postcode,post) VALUES (2242,'Zgornja Korena');
INSERT INTO posts (postcode,post) VALUES (2250,'Ptuj');
INSERT INTO posts (postcode,post) VALUES (2251,'Ptuj');
INSERT INTO posts (postcode,post) VALUES (2252,'Dornava');
INSERT INTO posts (postcode,post) VALUES (2253,'Destrnik');
INSERT INTO posts (postcode,post) VALUES (2254,'Trnovska vas');
INSERT INTO posts (postcode,post) VALUES (2255,'Vitomarci');
INSERT INTO posts (postcode,post) VALUES (2256,'Juršinci');
INSERT INTO posts (postcode,post) VALUES (2257,'Polenšak');
INSERT INTO posts (postcode,post) VALUES (2258,'Sveti Tomaž');
INSERT INTO posts (postcode,post) VALUES (2259,'Ivanjkovci');
INSERT INTO posts (postcode,post) VALUES (2270,'Ormož');
INSERT INTO posts (postcode,post) VALUES (2272,'Gorišnica');
INSERT INTO posts (postcode,post) VALUES (2273,'Podgorci');
INSERT INTO posts (postcode,post) VALUES (2274,'Velika Nedelja');
INSERT INTO posts (postcode,post) VALUES (2275,'Miklavž pri Ormožu');
INSERT INTO posts (postcode,post) VALUES (2276,'Kog');
INSERT INTO posts (postcode,post) VALUES (2277,'Središce ob Dravi');
INSERT INTO posts (postcode,post) VALUES (2281,'Markovci');
INSERT INTO posts (postcode,post) VALUES (2282,'Cirkulane');
INSERT INTO posts (postcode,post) VALUES (2283,'Zavrc');
INSERT INTO posts (postcode,post) VALUES (2284,'Videm pri Ptuju');
INSERT INTO posts (postcode,post) VALUES (2285,'Zgornji Leskovec');
INSERT INTO posts (postcode,post) VALUES (2286,'Podlehnik');
INSERT INTO posts (postcode,post) VALUES (2287,'Žetale');
INSERT INTO posts (postcode,post) VALUES (2288,'Hajdina');
INSERT INTO posts (postcode,post) VALUES (2289,'Stoperce');
INSERT INTO posts (postcode,post) VALUES (2310,'Slovenska Bistrica');
INSERT INTO posts (postcode,post) VALUES (2311,'Hoce');
INSERT INTO posts (postcode,post) VALUES (2312,'Orehova vas');
INSERT INTO posts (postcode,post) VALUES (2313,'Fram');
INSERT INTO posts (postcode,post) VALUES (2314,'Zgornja Polskava');
INSERT INTO posts (postcode,post) VALUES (2315,'Šmartno na Pohorju');
INSERT INTO posts (postcode,post) VALUES (2316,'Zgornja Ložnica');
INSERT INTO posts (postcode,post) VALUES (2317,'Oplotnica');
INSERT INTO posts (postcode,post) VALUES (2318,'Laporje');
INSERT INTO posts (postcode,post) VALUES (2319,'Poljcane');
INSERT INTO posts (postcode,post) VALUES (2321,'Makole');
INSERT INTO posts (postcode,post) VALUES (2322,'Majšperk');
INSERT INTO posts (postcode,post) VALUES (2323,'Ptujska Gora');
INSERT INTO posts (postcode,post) VALUES (2324,'Lovrenc na Dravskem polju');
INSERT INTO posts (postcode,post) VALUES (2325,'Kidricevo');
INSERT INTO posts (postcode,post) VALUES (2326,'Cirkovce');
INSERT INTO posts (postcode,post) VALUES (2327,'Race');
INSERT INTO posts (postcode,post) VALUES (2331,'Pragersko');
INSERT INTO posts (postcode,post) VALUES (2341,'Limbuš');
INSERT INTO posts (postcode,post) VALUES (2342,'Ruše');
INSERT INTO posts (postcode,post) VALUES (2343,'Fala');
INSERT INTO posts (postcode,post) VALUES (2344,'Lovrenc na Pohorju');
INSERT INTO posts (postcode,post) VALUES (2345,'Bistrica ob Dravi');
INSERT INTO posts (postcode,post) VALUES (2351,'Kamnica');
INSERT INTO posts (postcode,post) VALUES (2352,'Selnica ob Dravi');
INSERT INTO posts (postcode,post) VALUES (2353,'Sveti Duh na Ostrem Vrhu');
INSERT INTO posts (postcode,post) VALUES (2354,'Bresternica');
INSERT INTO posts (postcode,post) VALUES (2360,'Radlje ob Dravi');
INSERT INTO posts (postcode,post) VALUES (2361,'Ožbalt');
INSERT INTO posts (postcode,post) VALUES (2362,'Kapla');
INSERT INTO posts (postcode,post) VALUES (2363,'Podvelka');
INSERT INTO posts (postcode,post) VALUES (2364,'Ribnica na Pohorju');
INSERT INTO posts (postcode,post) VALUES (2365,'Vuhred');
INSERT INTO posts (postcode,post) VALUES (2366,'Muta');
INSERT INTO posts (postcode,post) VALUES (2367,'Vuzenica');
INSERT INTO posts (postcode,post) VALUES (2370,'Dravograd');
INSERT INTO posts (postcode,post) VALUES (2371,'Trbonje');
INSERT INTO posts (postcode,post) VALUES (2372,'Libelice');
INSERT INTO posts (postcode,post) VALUES (2373,'Šentjanž pri Dravogradu');
INSERT INTO posts (postcode,post) VALUES (2380,'Slovenj Gradec');
INSERT INTO posts (postcode,post) VALUES (2381,'Podgorje pri Slovenj Gradcu');
INSERT INTO posts (postcode,post) VALUES (2382,'Mislinja');
INSERT INTO posts (postcode,post) VALUES (2383,'Šmartno pri Slovenj Gradcu');
INSERT INTO posts (postcode,post) VALUES (2390,'Ravne na Koroškem');
INSERT INTO posts (postcode,post) VALUES (2391,'Prevalje');
INSERT INTO posts (postcode,post) VALUES (2392,'Mežica');
INSERT INTO posts (postcode,post) VALUES (2393,'Crna na Koroškem');
INSERT INTO posts (postcode,post) VALUES (2394,'Kotlje');
INSERT INTO posts (postcode,post) VALUES (2500,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2501,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2502,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2503,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2504,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2505,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2506,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2507,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2508,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2509,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2600,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2603,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2609,'Maribor');
INSERT INTO posts (postcode,post) VALUES (2610,'Maribor');
INSERT INTO posts (postcode,post) VALUES (3000,'Celje ');
INSERT INTO posts (postcode,post) VALUES (3001,'Celje - poštni predali');
INSERT INTO posts (postcode,post) VALUES (3201,'Šmartno v Rožni dolini');
INSERT INTO posts (postcode,post) VALUES (3202,'Ljubecna');
INSERT INTO posts (postcode,post) VALUES (3203,'Nova Cerkev');
INSERT INTO posts (postcode,post) VALUES (3204,'Dobrna');
INSERT INTO posts (postcode,post) VALUES (3205,'Vitanje');
INSERT INTO posts (postcode,post) VALUES (3206,'Stranice');
INSERT INTO posts (postcode,post) VALUES (3210,'Slovenske Konjice');
INSERT INTO posts (postcode,post) VALUES (3211,'Škofja vas');
INSERT INTO posts (postcode,post) VALUES (3212,'Vojnik');
INSERT INTO posts (postcode,post) VALUES (3213,'Frankolovo');
INSERT INTO posts (postcode,post) VALUES (3214,'Zrece');
INSERT INTO posts (postcode,post) VALUES (3215,'Loce');
INSERT INTO posts (postcode,post) VALUES (3220,'Štore');
INSERT INTO posts (postcode,post) VALUES (3221,'Teharje');
INSERT INTO posts (postcode,post) VALUES (3222,'Dramlje');
INSERT INTO posts (postcode,post) VALUES (3223,'Loka pri Žusmu');
INSERT INTO posts (postcode,post) VALUES (3224,'Dobje pri Planini');
INSERT INTO posts (postcode,post) VALUES (3225,'Planina pri Sevnici');
INSERT INTO posts (postcode,post) VALUES (3230,'Šentjur');
INSERT INTO posts (postcode,post) VALUES (3231,'Grobelno');
INSERT INTO posts (postcode,post) VALUES (3232,'Ponikva');
INSERT INTO posts (postcode,post) VALUES (3233,'Kalobje');
INSERT INTO posts (postcode,post) VALUES (3240,'Šmarje pri Jelšah');
INSERT INTO posts (postcode,post) VALUES (3241,'Podplat');
INSERT INTO posts (postcode,post) VALUES (3250,'Rogaška Slatina');
INSERT INTO posts (postcode,post) VALUES (3252,'Rogatec');
INSERT INTO posts (postcode,post) VALUES (3253,'Pristava pri Mestinju');
INSERT INTO posts (postcode,post) VALUES (3254,'Podcetrtek');
INSERT INTO posts (postcode,post) VALUES (3255,'Buce');
INSERT INTO posts (postcode,post) VALUES (3256,'Bistrica ob Sotli');
INSERT INTO posts (postcode,post) VALUES (3257,'Podsreda');
INSERT INTO posts (postcode,post) VALUES (3260,'Kozje');
INSERT INTO posts (postcode,post) VALUES (3261,'Lesicno');
INSERT INTO posts (postcode,post) VALUES (3262,'Prevorje');
INSERT INTO posts (postcode,post) VALUES (3263,'Gorica pri Slivnici');
INSERT INTO posts (postcode,post) VALUES (3264,'Sveti Štefan');
INSERT INTO posts (postcode,post) VALUES (3270,'Laško');
INSERT INTO posts (postcode,post) VALUES (3271,'Šentrupert');
INSERT INTO posts (postcode,post) VALUES (3272,'Rimske Toplice');
INSERT INTO posts (postcode,post) VALUES (3273,'Jurklošter');
INSERT INTO posts (postcode,post) VALUES (3301,'Petrovce');
INSERT INTO posts (postcode,post) VALUES (3302,'Griže');
INSERT INTO posts (postcode,post) VALUES (3303,'Gomilsko');
INSERT INTO posts (postcode,post) VALUES (3304,'Tabor');
INSERT INTO posts (postcode,post) VALUES (3305,'Vransko');
INSERT INTO posts (postcode,post) VALUES (3310,'Žalec');
INSERT INTO posts (postcode,post) VALUES (3311,'Šempeter v Savinjski dolini');
INSERT INTO posts (postcode,post) VALUES (3312,'Prebold');
INSERT INTO posts (postcode,post) VALUES (3313,'Polzela');
INSERT INTO posts (postcode,post) VALUES (3314,'Braslovce');
INSERT INTO posts (postcode,post) VALUES (3320,'Velenje ');
INSERT INTO posts (postcode,post) VALUES (3322,'Velenje - poštni predali');
INSERT INTO posts (postcode,post) VALUES (3325,'Šoštanj');
INSERT INTO posts (postcode,post) VALUES (3326,'Topolšica');
INSERT INTO posts (postcode,post) VALUES (3327,'Šmartno ob Paki');
INSERT INTO posts (postcode,post) VALUES (3330,'Mozirje');
INSERT INTO posts (postcode,post) VALUES (3331,'Nazarje');
INSERT INTO posts (postcode,post) VALUES (3332,'Recica ob Savinji');
INSERT INTO posts (postcode,post) VALUES (3333,'Ljubno ob Savinji');
INSERT INTO posts (postcode,post) VALUES (3334,'Luce');
INSERT INTO posts (postcode,post) VALUES (3335,'Solcava');
INSERT INTO posts (postcode,post) VALUES (3341,'Šmartno ob Dreti');
INSERT INTO posts (postcode,post) VALUES (3342,'Gornji Grad');
INSERT INTO posts (postcode,post) VALUES (3503,'Velenje');
INSERT INTO posts (postcode,post) VALUES (3504,'Velenje');
INSERT INTO posts (postcode,post) VALUES (3505,'Celje');
INSERT INTO posts (postcode,post) VALUES (3600,'Celje');
INSERT INTO posts (postcode,post) VALUES (4000,'Kranj ');
INSERT INTO posts (postcode,post) VALUES (4001,'Kranj - poštni predali');
INSERT INTO posts (postcode,post) VALUES (4200,'Kranj');
INSERT INTO posts (postcode,post) VALUES (4201,'Zgornja Besnica');
INSERT INTO posts (postcode,post) VALUES (4202,'Naklo');
INSERT INTO posts (postcode,post) VALUES (4203,'Duplje');
INSERT INTO posts (postcode,post) VALUES (4204,'Golnik');
INSERT INTO posts (postcode,post) VALUES (4205,'Preddvor');
INSERT INTO posts (postcode,post) VALUES (4206,'Zgornje Jezersko');
INSERT INTO posts (postcode,post) VALUES (4207,'Cerklje na Gorenjskem');
INSERT INTO posts (postcode,post) VALUES (4208,'Šencur');
INSERT INTO posts (postcode,post) VALUES (4209,'Žabnica');
INSERT INTO posts (postcode,post) VALUES (4210,'Brnik - Aerodrom');
INSERT INTO posts (postcode,post) VALUES (4211,'Mavcice');
INSERT INTO posts (postcode,post) VALUES (4212,'Visoko');
INSERT INTO posts (postcode,post) VALUES (4220,'Škofja Loka');
INSERT INTO posts (postcode,post) VALUES (4223,'Poljane nad Škofjo Loko');
INSERT INTO posts (postcode,post) VALUES (4224,'Gorenja vas');
INSERT INTO posts (postcode,post) VALUES (4225,'Sovodenj');
INSERT INTO posts (postcode,post) VALUES (4226,'Žiri');
INSERT INTO posts (postcode,post) VALUES (4227,'Selca');
INSERT INTO posts (postcode,post) VALUES (4228,'Železniki');
INSERT INTO posts (postcode,post) VALUES (4229,'Sorica');
INSERT INTO posts (postcode,post) VALUES (4240,'Radovljica');
INSERT INTO posts (postcode,post) VALUES (4243,'Brezje');
INSERT INTO posts (postcode,post) VALUES (4244,'Podnart');
INSERT INTO posts (postcode,post) VALUES (4245,'Kropa');
INSERT INTO posts (postcode,post) VALUES (4246,'Kamna Gorica');
INSERT INTO posts (postcode,post) VALUES (4247,'Zgornje Gorje');
INSERT INTO posts (postcode,post) VALUES (4248,'Lesce');
INSERT INTO posts (postcode,post) VALUES (4260,'Bled');
INSERT INTO posts (postcode,post) VALUES (4263,'Bohinjska Bela');
INSERT INTO posts (postcode,post) VALUES (4264,'Bohinjska Bistrica');
INSERT INTO posts (postcode,post) VALUES (4265,'Bohinjsko jezero');
INSERT INTO posts (postcode,post) VALUES (4267,'Srednja vas v Bohinju');
INSERT INTO posts (postcode,post) VALUES (4270,'Jesenice');
INSERT INTO posts (postcode,post) VALUES (4273,'Blejska Dobrava');
INSERT INTO posts (postcode,post) VALUES (4274,'Žirovnica');
INSERT INTO posts (postcode,post) VALUES (4275,'Begunje na Gorenjskem');
INSERT INTO posts (postcode,post) VALUES (4276,'Hrušica');
INSERT INTO posts (postcode,post) VALUES (4280,'Kranjska Gora');
INSERT INTO posts (postcode,post) VALUES (4281,'Mojstrana');
INSERT INTO posts (postcode,post) VALUES (4282,'Gozd Martuljek');
INSERT INTO posts (postcode,post) VALUES (4283,'Ratece - Planica');
INSERT INTO posts (postcode,post) VALUES (4290,'Tržic');
INSERT INTO posts (postcode,post) VALUES (4294,'Križe');
INSERT INTO posts (postcode,post) VALUES (4501,'Naklo');
INSERT INTO posts (postcode,post) VALUES (4502,'Kranj');
INSERT INTO posts (postcode,post) VALUES (4600,'Kranj');
INSERT INTO posts (postcode,post) VALUES (5000,'Nova Gorica ');
INSERT INTO posts (postcode,post) VALUES (5001,'Nova Gorica - poštni predali');
INSERT INTO posts (postcode,post) VALUES (5210,'Deskle');
INSERT INTO posts (postcode,post) VALUES (5211,'Kojsko');
INSERT INTO posts (postcode,post) VALUES (5212,'Dobrovo v Brdih');
INSERT INTO posts (postcode,post) VALUES (5213,'Kanal');
INSERT INTO posts (postcode,post) VALUES (5214,'Kal nad Kanalom');
INSERT INTO posts (postcode,post) VALUES (5215,'Rocinj');
INSERT INTO posts (postcode,post) VALUES (5216,'Most na Soci');
INSERT INTO posts (postcode,post) VALUES (5220,'Tolmin');
INSERT INTO posts (postcode,post) VALUES (5222,'Kobarid');
INSERT INTO posts (postcode,post) VALUES (5223,'Breginj');
INSERT INTO posts (postcode,post) VALUES (5224,'Srpenica');
INSERT INTO posts (postcode,post) VALUES (5230,'Bovec');
INSERT INTO posts (postcode,post) VALUES (5231,'Log pod Mangartom');
INSERT INTO posts (postcode,post) VALUES (5232,'Soca');
INSERT INTO posts (postcode,post) VALUES (5242,'Grahovo ob Baci');
INSERT INTO posts (postcode,post) VALUES (5243,'Podbrdo');
INSERT INTO posts (postcode,post) VALUES (5250,'Solkan');
INSERT INTO posts (postcode,post) VALUES (5251,'Grgar');
INSERT INTO posts (postcode,post) VALUES (5252,'Trnovo pri Gorici');
INSERT INTO posts (postcode,post) VALUES (5253,'Cepovan');
INSERT INTO posts (postcode,post) VALUES (5261,'Šempas');
INSERT INTO posts (postcode,post) VALUES (5262,'Crnice');
INSERT INTO posts (postcode,post) VALUES (5263,'Dobravlje');
INSERT INTO posts (postcode,post) VALUES (5270,'Ajdovšcina');
INSERT INTO posts (postcode,post) VALUES (5271,'Vipava');
INSERT INTO posts (postcode,post) VALUES (5272,'Podnanos');
INSERT INTO posts (postcode,post) VALUES (5273,'Col');
INSERT INTO posts (postcode,post) VALUES (5274,'Crni Vrh nad Idrijo');
INSERT INTO posts (postcode,post) VALUES (5275,'Godovic');
INSERT INTO posts (postcode,post) VALUES (5280,'Idrija');
INSERT INTO posts (postcode,post) VALUES (5281,'Spodnja Idrija');
INSERT INTO posts (postcode,post) VALUES (5282,'Cerkno');
INSERT INTO posts (postcode,post) VALUES (5283,'Slap ob Idrijci');
INSERT INTO posts (postcode,post) VALUES (5290,'Šempeter pri Gorici');
INSERT INTO posts (postcode,post) VALUES (5291,'Miren');
INSERT INTO posts (postcode,post) VALUES (5292,'Rence');
INSERT INTO posts (postcode,post) VALUES (5293,'Volcja Draga');
INSERT INTO posts (postcode,post) VALUES (5294,'Dornberk');
INSERT INTO posts (postcode,post) VALUES (5295,'Branik');
INSERT INTO posts (postcode,post) VALUES (5296,'Kostanjevica na Krasu');
INSERT INTO posts (postcode,post) VALUES (5297,'Prvacina');
INSERT INTO posts (postcode,post) VALUES (5600,'Nova Gorica');
INSERT INTO posts (postcode,post) VALUES (6000,'Koper/Capodistria ');
INSERT INTO posts (postcode,post) VALUES (6001,'Koper/Capodistria - poštni predali');
INSERT INTO posts (postcode,post) VALUES (6200,'Koper');
INSERT INTO posts (postcode,post) VALUES (6210,'Sežana');
INSERT INTO posts (postcode,post) VALUES (6215,'Divaca');
INSERT INTO posts (postcode,post) VALUES (6216,'Podgorje');
INSERT INTO posts (postcode,post) VALUES (6217,'Vremski Britof');
INSERT INTO posts (postcode,post) VALUES (6219,'Lokev');
INSERT INTO posts (postcode,post) VALUES (6221,'Dutovlje');
INSERT INTO posts (postcode,post) VALUES (6222,'Štanjel');
INSERT INTO posts (postcode,post) VALUES (6223,'Komen');
INSERT INTO posts (postcode,post) VALUES (6224,'Senožece');
INSERT INTO posts (postcode,post) VALUES (6225,'Hruševje');
INSERT INTO posts (postcode,post) VALUES (6230,'Postojna');
INSERT INTO posts (postcode,post) VALUES (6232,'Planina');
INSERT INTO posts (postcode,post) VALUES (6240,'Kozina');
INSERT INTO posts (postcode,post) VALUES (6242,'Materija');
INSERT INTO posts (postcode,post) VALUES (6243,'Obrov');
INSERT INTO posts (postcode,post) VALUES (6244,'Podgrad');
INSERT INTO posts (postcode,post) VALUES (6250,'Ilirska Bistrica');
INSERT INTO posts (postcode,post) VALUES (6251,'Ilirska Bistrica-Trnovo');
INSERT INTO posts (postcode,post) VALUES (6253,'Knežak');
INSERT INTO posts (postcode,post) VALUES (6254,'Jelšane');
INSERT INTO posts (postcode,post) VALUES (6255,'Prem');
INSERT INTO posts (postcode,post) VALUES (6256,'Košana');
INSERT INTO posts (postcode,post) VALUES (6257,'Pivka');
INSERT INTO posts (postcode,post) VALUES (6258,'Prestranek');
INSERT INTO posts (postcode,post) VALUES (6271,'Dekani');
INSERT INTO posts (postcode,post) VALUES (6272,'Gracišce');
INSERT INTO posts (postcode,post) VALUES (6273,'Marezige');
INSERT INTO posts (postcode,post) VALUES (6274,'Šmarje');
INSERT INTO posts (postcode,post) VALUES (6275,'Crni Kal');
INSERT INTO posts (postcode,post) VALUES (6276,'Pobegi');
INSERT INTO posts (postcode,post) VALUES (6280,'Ankaran/Ancarano');
INSERT INTO posts (postcode,post) VALUES (6281,'Škofije');
INSERT INTO posts (postcode,post) VALUES (6310,'Izola/Isola');
INSERT INTO posts (postcode,post) VALUES (6320,'Portorož/Portorose');
INSERT INTO posts (postcode,post) VALUES (6330,'Piran/Pirano');
INSERT INTO posts (postcode,post) VALUES (6333,'Secovlje/Sicciole');
INSERT INTO posts (postcode,post) VALUES (6501,'Koper');
INSERT INTO posts (postcode,post) VALUES (6502,'Koper');
INSERT INTO posts (postcode,post) VALUES (6503,'Koper');
INSERT INTO posts (postcode,post) VALUES (6504,'Koper');
INSERT INTO posts (postcode,post) VALUES (6600,'Koper');
INSERT INTO posts (postcode,post) VALUES (8000,'Novo mesto');
INSERT INTO posts (postcode,post) VALUES (8001,'Novo mesto - poštni predali');
INSERT INTO posts (postcode,post) VALUES (8210,'Trebnje');
INSERT INTO posts (postcode,post) VALUES (8211,'Dobrnic');
INSERT INTO posts (postcode,post) VALUES (8212,'Velika Loka');
INSERT INTO posts (postcode,post) VALUES (8213,'Veliki Gaber');
INSERT INTO posts (postcode,post) VALUES (8216,'Mirna Pec');
INSERT INTO posts (postcode,post) VALUES (8220,'Šmarješke Toplice');
INSERT INTO posts (postcode,post) VALUES (8222,'Otocec');
INSERT INTO posts (postcode,post) VALUES (8230,'Mokronog');
INSERT INTO posts (postcode,post) VALUES (8231,'Trebelno ');
INSERT INTO posts (postcode,post) VALUES (8232,'Šentrupert');
INSERT INTO posts (postcode,post) VALUES (8233,'Mirna');
INSERT INTO posts (postcode,post) VALUES (8250,'Brežice');
INSERT INTO posts (postcode,post) VALUES (8251,'Catež ob Savi');
INSERT INTO posts (postcode,post) VALUES (8253,'Artice');
INSERT INTO posts (postcode,post) VALUES (8254,'Globoko');
INSERT INTO posts (postcode,post) VALUES (8255,'Pišece');
INSERT INTO posts (postcode,post) VALUES (8256,'Sromlje ');
INSERT INTO posts (postcode,post) VALUES (8257,'Dobova');
INSERT INTO posts (postcode,post) VALUES (8258,'Kapele');
INSERT INTO posts (postcode,post) VALUES (8259,'Bizeljsko');
INSERT INTO posts (postcode,post) VALUES (8261,'Jesenice na Dolenjskem');
INSERT INTO posts (postcode,post) VALUES (8262,'Krška vas');
INSERT INTO posts (postcode,post) VALUES (8263,'Cerklje ob Krki');
INSERT INTO posts (postcode,post) VALUES (8270,'Krško');
INSERT INTO posts (postcode,post) VALUES (8272,'Zdole ');
INSERT INTO posts (postcode,post) VALUES (8273,'Leskovec pri Krškem');
INSERT INTO posts (postcode,post) VALUES (8274,'Raka');
INSERT INTO posts (postcode,post) VALUES (8275,'Škocjan');
INSERT INTO posts (postcode,post) VALUES (8276,'Bucka ');
INSERT INTO posts (postcode,post) VALUES (8280,'Brestanica');
INSERT INTO posts (postcode,post) VALUES (8281,'Senovo');
INSERT INTO posts (postcode,post) VALUES (8282,'Koprivnica');
INSERT INTO posts (postcode,post) VALUES (8283,'Blanca');
INSERT INTO posts (postcode,post) VALUES (8290,'Sevnica');
INSERT INTO posts (postcode,post) VALUES (8292,'Zabukovje ');
INSERT INTO posts (postcode,post) VALUES (8293,'Studenec');
INSERT INTO posts (postcode,post) VALUES (8294,'Boštanj');
INSERT INTO posts (postcode,post) VALUES (8295,'Tržišce');
INSERT INTO posts (postcode,post) VALUES (8296,'Krmelj');
INSERT INTO posts (postcode,post) VALUES (8297,'Šentjanž');
INSERT INTO posts (postcode,post) VALUES (8310,'Šentjernej');
INSERT INTO posts (postcode,post) VALUES (8311,'Kostanjevica na Krki');
INSERT INTO posts (postcode,post) VALUES (8312,'Podbocje');
INSERT INTO posts (postcode,post) VALUES (8321,'Brusnice');
INSERT INTO posts (postcode,post) VALUES (8322,'Stopice');
INSERT INTO posts (postcode,post) VALUES (8323,'Uršna sela');
INSERT INTO posts (postcode,post) VALUES (8330,'Metlika');
INSERT INTO posts (postcode,post) VALUES (8331,'Suhor');
INSERT INTO posts (postcode,post) VALUES (8332,'Gradac');
INSERT INTO posts (postcode,post) VALUES (8333,'Semic');
INSERT INTO posts (postcode,post) VALUES (8340,'Crnomelj');
INSERT INTO posts (postcode,post) VALUES (8341,'Adlešici');
INSERT INTO posts (postcode,post) VALUES (8342,'Stari trg ob Kolpi');
INSERT INTO posts (postcode,post) VALUES (8343,'Dragatuš');
INSERT INTO posts (postcode,post) VALUES (8344,'Vinica');
INSERT INTO posts (postcode,post) VALUES (8350,'Dolenjske Toplice');
INSERT INTO posts (postcode,post) VALUES (8351,'Straža');
INSERT INTO posts (postcode,post) VALUES (8360,'Žužemberk');
INSERT INTO posts (postcode,post) VALUES (8361,'Dvor');
INSERT INTO posts (postcode,post) VALUES (8362,'Hinje');
INSERT INTO posts (postcode,post) VALUES (8501,'Novo mesto');
INSERT INTO posts (postcode,post) VALUES (8600,'Novo mesto');
INSERT INTO posts (postcode,post) VALUES (9000,'Murska Sobota ');
INSERT INTO posts (postcode,post) VALUES (9001,'Murska Sobota - poštni predali');
INSERT INTO posts (postcode,post) VALUES (9201,'Puconci');
INSERT INTO posts (postcode,post) VALUES (9202,'Mackovci');
INSERT INTO posts (postcode,post) VALUES (9203,'Petrovci');
INSERT INTO posts (postcode,post) VALUES (9204,'Šalovci');
INSERT INTO posts (postcode,post) VALUES (9205,'Hodoš/Hodos');
INSERT INTO posts (postcode,post) VALUES (9206,'Križevci');
INSERT INTO posts (postcode,post) VALUES (9207,'Prosenjakovci/Partosfalva');
INSERT INTO posts (postcode,post) VALUES (9208,'Fokovci');
INSERT INTO posts (postcode,post) VALUES (9220,'Lendava/Lendva');
INSERT INTO posts (postcode,post) VALUES (9221,'Martjanci');
INSERT INTO posts (postcode,post) VALUES (9222,'Bogojina');
INSERT INTO posts (postcode,post) VALUES (9223,'Dobrovnik/Dobronak ');
INSERT INTO posts (postcode,post) VALUES (9224,'Turnišce');
INSERT INTO posts (postcode,post) VALUES (9225,'Velika Polana');
INSERT INTO posts (postcode,post) VALUES (9226,'Moravske Toplice');
INSERT INTO posts (postcode,post) VALUES (9227,'Kobilje');
INSERT INTO posts (postcode,post) VALUES (9231,'Beltinci');
INSERT INTO posts (postcode,post) VALUES (9232,'Crenšovci');
INSERT INTO posts (postcode,post) VALUES (9233,'Odranci');
INSERT INTO posts (postcode,post) VALUES (9240,'Ljutomer');
INSERT INTO posts (postcode,post) VALUES (9241,'Veržej');
INSERT INTO posts (postcode,post) VALUES (9242,'Križevci pri Ljutomeru');
INSERT INTO posts (postcode,post) VALUES (9243,'Mala Nedelja');
INSERT INTO posts (postcode,post) VALUES (9244,'Sveti Jurij ob Šcavnici');
INSERT INTO posts (postcode,post) VALUES (9245,'Spodnji Ivanjci');
INSERT INTO posts (postcode,post) VALUES (9246,'Razkrižje');
INSERT INTO posts (postcode,post) VALUES (9250,'Gornja Radgona');
INSERT INTO posts (postcode,post) VALUES (9251,'Tišina');
INSERT INTO posts (postcode,post) VALUES (9252,'Radenci');
INSERT INTO posts (postcode,post) VALUES (9253,'Apace');
INSERT INTO posts (postcode,post) VALUES (9261,'Cankova');
INSERT INTO posts (postcode,post) VALUES (9262,'Rogašovci');
INSERT INTO posts (postcode,post) VALUES (9263,'Kuzma');
INSERT INTO posts (postcode,post) VALUES (9264,'Grad');
INSERT INTO posts (postcode,post) VALUES (9265,'Bodonci');
INSERT INTO posts (postcode,post) VALUES (9501,'Murska Sobota');
INSERT INTO posts (postcode,post) VALUES (9502,'Radenci');
INSERT INTO posts (postcode,post) VALUES (9600,'Murska Sobota');
